### ISSUE TITLE
Rename editor func from key combo to behavioral naming base.

### ISSUE THREAD

**Issue by kaio** [kaio/ibus-table#15]
There are functions in editor class that named after key combinations. This is less appropriate as key combinations are easier to be changed along development or user customization. 

Proposed renaming functions:
- [x] arrow_down
- [ ] arrow_left
- [ ] arrow_right
- [x] arrow_up
- [x] backspace
- [ ] control_arrow_left
- [ ] control_arrow_right
- [x] control_backspace
- [ ] control_delete
- [ ] delete
- [x] l_alt
- [ ] l_shift
- [x] page_down
- [x] page_up
- [ ] r_shift
- [ ] space

All other functions are not going to be processed unless when they are obviously needed to be renamed.

**Comment by mike-fabian** [comment]
I think the code has changed so much since this issue was opened, it is better to close it and if necessary open new issues agains the current code.
