### ISSUE TITLE
分号；单引号，上屏

### ISSUE THREAD

**Issue by unihon** [kaio/ibus-table#60]
通过分号`；`单引号`，`选择 2\3 号字、组上屏功能是否支持？

**Comment by Joe-C-Ding** [comment]
我也问过#57，作者说现在按键是跟随码表定义的，不能自己改。

但之后我试了把选择 2/3 的键改成 `;` 和 `'`（不管是全角还是半角），再从改后的码表生成自己的词库。实际的效果是 `2` 和 `3` 不能用来选词了，但  `;` 和 `'` 也还是不行。不知道是不是系统还有其它限制。

**Comment by unihon** [comment]
> 我也问过#57，作者说现在按键是跟随码表定义的，不能自己改。
> 
> 但之后我试了把选择 2/3 的键改成 `;` 和 `'`（不管是全角还是半角），再从改后的码表生成自己的词库。实际的效果是 `2` 和 `3` 不能用来选词了，但 `;` 和 `'` 也还是不行。不知道是不是系统还有其它限制。

我已经投奔 rime 了，也是一个不错的输入法。
