### ISSUE TITLE
Cangjie 5 not working if auto wildcard turned off 

### ISSUE THREAD

**Issue by maxloh** [kaio/ibus-table#61]
With the "auto wildcard" option is set to "No", Canjie 5 behaves like quick input method. I can't type Chinese characters with more than 2 character components.

**Comment by mike-fabian** [comment]
How exactly should Cangjie 5 work with the “auto wildcard” option set to “No”?

**Comment by mike-fabian** [comment]
I tested again, and with the “auto wildcard” option set to “No”, Cangie5 does **not** behave like the quick5 input method.

With “auto wildcard” set to no, when typing “ah”, the cangjie5 input method matches a single character, this one:

```
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables (master)
$ grep  '^ah\s' cangjie/cangjie5.txt 
ah      𠃜      1000
```

This is exactly as expected from the cangjie5 table, when no wildcard is automatically added after the input.

When using quick5 however, typing “ah” matches a log more characters, and that is expected as there are
a lot more exact matches for the input “ah” in the quick5 table:

```
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables (master)
$ grep  '^ah\s' quick/quick5.txt 
ah      𣊱      1000
ah      𢒠      1000
ah      𣋥      1000
ah      𣌥      1000
ah      𣌤      1000
ah      𠃜      1000
ah      𣊷      1000
ah      𢒗      1000
ah      𣆈      1000
ah      𨵶      1000
ah      𨳚      1000
ah      𨉖      1000
ah      𨴸      1000
ah      𨴒      1000
ah      𨶪      1000
ah      𢒧      1000
ah      𣆄      1000
ah      㬔      1000
ah      尟      1000
ah      影      1000
ah      旫      1000
ah      旸      1000
ah      昐      1000
ah      昒      1000
ah      易      1000
ah      昜      1000
ah      昣      1000
ah      晜      1000
ah      晹      1000
ah      暘      1000
ah      曑      1000
ah      閁      1000
ah      閉      1000
ah      閕      1000
ah      閟      1000
ah      閯      1000
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables (master)
$ 
```

So to me this looks as if it works exactly as expected.

**Comment by maxloh** [comment]
Thx. I experience the bug in older version of Ubuntu/IBus Table. 

I just test again in Ubuntu 20.04, and it works like a charm :)
