### ISSUE TITLE
多窗口使用ibus-table卡顿

### ISSUE THREAD

**Issue by yueduz** [kaio/ibus-table#62]
在Gnome中，当我同时在两个窗口激活了ibus-table输入法后，切换两个窗口会卡顿。使用ibus-libpinyin就不就不会有这种问题。

**Comment by mike-fabian** [comment]
In Gnome, when I activate the ibus-table input method in two windows at the same time, switching between the two windows will freeze. If you use ibus-libpinyin, there will be no such problems.

**Comment by yueduz** [comment]
我今天又试了一下，我的系统是archlinux，ibus版本是1.10.0-1。不会在出现卡顿。我不知道是因为更新了系统还是更新了输入法。
