### ISSUE TITLE
Weird prefix matching instead of exact matching in pinyin search

### ISSUE THREAD

**Issue by champignoom** [kaio/ibus-table#63]
https://github.com/kaio/ibus-table/blob/8120e5fa3597a021d6a3b50f132dcbcae4501829/engine/tabsqlitedb.py#L1141

It hardly ever makes sense to prioritize a character with different pinyin from intended just because it has higher frequency, especially when there are dozens of such kind of characters, which are extremely annoying to skip over.

Please change the prefix matching to exact equality, unless it was a native speaker's decision to do prefix matching with serious reasons.

**Comment by mike-fabian** [comment]
You don’t want to see the matches for “ling” when you have only typed “lin” do I understand that correctly?

What about the tones? Do you also want to see only exact matches there? I.e. if you “lin” you see nothing, only if you type for example “lin@" (@ is Shift+2, i.e. tone 2) you want to see the matches 林, 琳, 隣, ... ?

Is that right?

Maybe I should add another option “Auto wildcard for pinyin: [Yes/No]”, similar to the already existing “Auto wildcard: [Yes/No]” option?

**Comment by mike-fabian** [comment]
And if I add such an option, the default should be "No", i.e. exact matching?

**Comment by mike-fabian** [comment]
Or, maybe it is enough to put the exact matches on top also for pinyin and I don't need an option?
The commit you mention:

https://github.com/kaio/ibus-table/commit/f795793bdaa28d06787c334b2acf7e9ad6223501

does this only when not in pinyin mode.

**Comment by mike-fabian** [comment]
I think I try putting the exact matches on top first and see whether that is good enough, then we probably do not need a new option.

**Comment by champignoom** [comment]
I would suggest to do exact matching *only*, as long as no objections of it has been given before:
1. Pinyins are names of categories of characters with at most 6 letters and clear structures, which no one who needs it would forget or feel too long to type, especially when it's the backup option or even the dictionary for another input method.
2. The current pinyin mode already has perceivable but *unnecessary* lagging. When one has to wait for 100ms after typing 'l' just to wait for the engine to fetch tens of thousands of characters that starts with 'l' where none is helpful except for one that hides in the 225th page, this is particularly annoying.

**Comment by champignoom** [comment]
> What about the tones? Do you also want to see only exact matches there? I.e. if you “lin” you see nothing, only if you type for example “lin@" (@ is Shift+2, i.e. tone 2) you want to see the matches 林, 琳, 隣, ... ?

This might become helpful when the user can somehow know about this information during typing without browsing github for documentations or even source code. At the moment this is not necessary imo.

> Maybe I should add another option “Auto wildcard for pinyin: [Yes/No]”, similar to the already existing “Auto wildcard: [Yes/No]” option? And if I add such an option, the default should be "No", i.e. exact matching?

I would argue that less is more. For the moment I don't see a nontrivial benefit that this additional complication brings.

**Comment by mike-fabian** [comment]
Yes, I also would like to avoid adding another option, if it is not necessary.

I am not sure whether I understood your answer concerning my question about the tones.

Should "lin" already match 林, or should only lin2 match 林? 

I.e. if a pinyin without the tone is entered, should candidates be shown or not?

**Comment by champignoom** [comment]
> I.e. if a pinyin without the tone is entered, should candidates be shown or not? Just tell me what you would prefer and I’ll try to do it.

I meat to stay status quo with regards to tones, that is, "lin" should already match 林 without specifying "2".

The idea is, roughly speaking, usability > performance > fancy stuffs.
Without enough resource and time to analyze the trade-offs, I would recommend sticking with usability.

Usability includes not annoying users by pages of unrelated characters which it currently risks, or confusing users with empty results when they enter "lin" and expecting to see something without knowing that an extra "2" is necessary.

Fancy stuffs like prefix matching or tones could still be added without sacrificing usability or perceivable decrease of efficiency.
I'm no expert on sql but, for example, if paging together with index on (pinyin, frequency) could prioritize exact matches without ignoring prefix matches when few or no exact matches are there, and achieve this without scanning through all matches or even the whole database when one type a letter and expecting nothing but ten of them, then prefix matching is good.
Similarly, if the users are hinted somewhere that pressing "shift" is useful, and when they do it, the four tones appear either beside the candidates or at the top or bottom, so that the users learn this functionality through interaction while remain capable of using the application without knowing this, then tones are helpful.

But of course, these are all optional and should only implemented after a more serious discussion and decision about the design.

**Comment by mike-fabian** [comment]
> > I.e. if a pinyin without the tone is entered, should candidates be shown or not? Just tell me what you would prefer and I’ll try to do it.
> 
> I meant to stay status quo with regards to tones, that is, "lin" should already match 林 without specifying "2".

OK, thank you! I’ll try to do that.

**Comment by mike-fabian** [comment]
I think I have something which is fast and works much better than before.

Typing “lin” in pinyin mode (in simplified Chinese mode) now gives:

![Screenshot](https://user-images.githubusercontent.com/2330175/91303268-0ef9df00-e7a8-11ea-96e7-72cbc41d7526.png)

**Comment by mike-fabian** [comment]
And typing “lia” in pinyin mode (in simplified Chinese mode) now gives:

![Screenshot](https://user-images.githubusercontent.com/2330175/91303459-597b5b80-e7a8-11ea-8b4b-de2841d4e982.png)

**Comment by mike-fabian** [comment]
It is in ibus-table 1.12.0:

https://github.com/mike-fabian/ibus-table/releases/tag/1.12.0

**Comment by champignoom** [comment]
Thanks, that looks perfect now.
