### ISSUE TITLE
<Esc> is not processed

### ISSUE THREAD

**Issue by champignoom** [kaio/ibus-table#64]
Environment: Manjaro 20.2, ibus 1.5.22, ibus table 1.12.1

How to reproduce:
1. Open firefox, press `<ctrl-f>` / open vim, type 'i'
2. Switch to any input method from ibus-table
3. Press `<Esc>`

Excepted:
Firefox's search bar should disappear, and vim should switch to normal mode.

Actual:
Nothing happens.

NB:
Other input methods from ibus handles `<Esc>` as expected.

**Comment by mike-fabian** [comment]
I think this would fix it:

https://github.com/mike-fabian/ibus-table/commit/ad95a9012fcf7a52ddc621934eabc3c52eb8c411

**Comment by champignoom** [comment]
Thanks for the fix!

**Comment by mike-fabian** [comment]
Thank you for testing, I pushed the fix to master and made a new release 1.12.3.
