### ISSUE TITLE
修改词条不生效

### ISSUE THREAD

**Issue by 354651432** [kaio/ibus-table#65]
极点五笔的某些词会导致 phpstorm 行为很奇怪 ,所以我想删除一些用不上的词, 数据库文件在 `/usr/share/ibus-table/tables/wubi-jidian86.db`, 我从里边删除了不需要的词 
```sql
delete from phrases where tabkeys="wftc" and phrase != "什么"
```
可是我重启 ibus `ibus restart` ,或者重启系统以后 `wftc` 对应的繁体字还在
操作系统为 manjaro 
`Linux dual-pc 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux`

**Comment by mike-fabian** [comment]
Automatic translation:

Some words in Extreme Wubi will cause phpstorm to behave strangely, so I want to delete some unused words. The database file is in /usr/share/ibus-table/tables/wubi-jidian86.db, I deleted it from inside. Needed word

```
delete from phrases where tabkeys="wftc" and phrase != "什么
```

But I restarted ibus ibus restart, or after restarting the system, the traditional characters corresponding to wftc are still there
Operating system is manjaro
Linux dual-pc 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux

**Comment by mike-fabian** [comment]
Looking at the sources of that wubi table I find:

```
$ grep wftc wubi-jidian86.txt 
wftc    什么    475000000
wftc    𥝈      0
wftc    𦦒      0
$
```

**Comment by 354651432** [comment]
> Is it possible that these characters are still in your user database in ~/.local/share/ibus-table/tables ?
> 
> Like this:
> 
> ```
> $ sqlite3 wubi-jidian86-user.db
> SQLite version 3.34.1 2021-01-20 14:10:07
> Enter ".help" for usage hints.
> sqlite> select * from phrases where tabkeys="wftc";
> 71|wftc|𥝈|0|1
> 72|wftc|𦦒|0|1
> sqlite> 
> ```
> 
> Maybe you only deleted them from the system database?

yes i fixed

**Comment by mike-fabian** [comment]
OK, thank you!
