### ISSUE TITLE
With dark theme, the candidates shown black text on dark background

### ISSUE THREAD

**Issue by mozbugbox** [kaio/ibus-table#67]
With the dark mode (Gtk dark mode?), the candidates were shown as black text over a dark grey background. The black text was not very legible.

The text should be light grey or some lighter color over the dark grey background. 

Actually, many of the items are not very legible under the dark theme.

![ibus-table-dark-theme](https://user-images.githubusercontent.com/1501849/111268425-3e027000-8668-11eb-88f9-a42c80da7f1a.png)

**Comment by mozbugbox** [comment]
I saw similar complain at https://github.com/ibus/ibus/issues/2205#issue-595828786 .

**Comment by mike-fabian** [comment]
Very interesting, testing your pull request...
