### ISSUE TITLE
Shift_L should commit English and switch mode when preedit not empty

### ISSUE THREAD

**Issue by mozbugbox** [kaio/ibus-table#68]
When a user pressed the `Shift_L` with the content of the preedit not-empty, it's most likely because the `English mode` was wanted. However the user did not aware that the mode was actually in the `table mode`. It was a mis-typing. Therefore the `Shift_L` key should had the English input commit and then switch to `direct mode`, i.e. fix the mistake and keep typing English.

That way, the user can continue the typing without interrupt. This is a more streaming behavior than the current one: commit the first candidate of the `table mode` and then do nothing. If the user want to commit the first candidates, the `space` key would be pressed.

**Comment by mike-fabian** [comment]
Sounds good, thank  you for your pull request, I am testing it.
