### ISSUE TITLE
ADD: Error sound and stop input if wrong code in Cangjie

### ISSUE THREAD

**Issue by WhiteCzar** [kaio/ibus-table#75]
Since we're kind of on a roll... forgive me another suggestion:
Is it possible to make Cangjie make error sound and stop input if one types the wrong code and presses space?
The way Cangjie works now is that if you type the wrong code and type space, nothing happens and you can just continue inputting a helluva lot letters without anything changing into any Chinese characters. Further IME switching is also blocked, so you will just be inputting code without anything happening and you may not even realize that if you aren't looking at the screen. This can be a big problem if you're touch typing while, for example, looking at a book (not on your screen) and inputting what's in the book into your PC. If you accidentally press the wrong key, the IME won't notify you and you may continue typing senselessly forever.
Needless to say, Microsoft Changjie has this feature this by default.

**Comment by mike-fabian** [comment]
Playing a beep sound on illegal input would be enough maybe?

**Comment by WhiteCzar** [comment]
Sure, this would alleviate the problem,

**Comment by mike-fabian** [comment]
I experimented with this and was successful in playing a .wav file using python3-simpleaudio on illegal input.

I wonder what .wav file makes a nice beep and has a compatible free license so I could include it in ibus-table.

I could also make it configurable and let the user specify the sound file:

     [ ✔️ ] Play .wav sound file on illegal input:     [/usr/share/ibus-table/data/beep.wav]

But I should probably include one default .wav file with ibus-table ...

**Comment by mike-fabian** [comment]
How about this as a default sound for invalid input?:

[coin9.wav](https://freesound.org/people/The-Sacha-Rush/sounds/336936/)

License is 

https://creativecommons.org/publicdomain/zero/1.0/ 

I.e. it is Public Domain, No Copyright.

I can probably use this as a default sound.

**Comment by WhiteCzar** [comment]
Haha that's a quirky sound, but why not. Could become a special characteristic error sound of iBus. Of course, the ability to change sounds (and turn them altogether) would be great, too. For people who might not want this sound or any error sound at all.

**Comment by mike-fabian** [comment]
If one doesn’t want an error sound at all, one could just uncheck the option.

Should the default for this option be on or off?

**Comment by WhiteCzar** [comment]
I think it should be on. This way people would know that this new feature exists. And cangjie is much more useful with this feature, I think.

**Comment by mike-fabian** [comment]
OK!

This is probably a better text for the option:

[ ✔️ ] Play sound file on error:     [/usr/share/ibus-table/data/beep.wav]

**Comment by WhiteCzar** [comment]
Yeah, this is better!

**Comment by mike-fabian** [comment]
Are you using Fedora? If yes, which version? I forgot ...

**Comment by mike-fabian** [comment]
If you are using fedora you can find builds form 1.13.4 here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/builds/

No official release yet, but these builds have the new option to beep on error, so you could test that if you like.

**Comment by WhiteCzar** [comment]
I'm using Pop_OS! right now. I tried installing Fedora 34 but there was some problem with the bootloader after the install. Sometimes it would boot, sometimes it wouldn't. Or maybe it was just a problem with my Microsoft Surface on which I installed Fedora.
Anyways, how can I test this on Pop_OS!? Or I can wait till the official release, too.

**Comment by mike-fabian** [comment]
Did you build from source on Pop_OS or use a package?

**Comment by WhiteCzar** [comment]
I'm using a package. I think it's an ordinary Ubuntu package.

**Comment by mike-fabian** [comment]
Does Ubuntu have up-to-date packages? 

https://repology.org/project/ibus-table/versions shows ibus-table-1.12.4 for Ubuntu 21.04.

**Comment by WhiteCzar** [comment]
Yeah, this would be the one. Mine says 1.12.4 in About.

**Comment by WhiteCzar** [comment]
I noticed a little bug. So when I make a typo it makes a sound - that's great. However, it also makes the sound whenever I try to erase the illegal input, which it weird. If I just press the Esc key, the whole input is refreshed and there is no sound. But Esc is too far away and so not very convenient when touch typing. Is it possible for ibus-table not to make the sound when you're Backspace-erasing illegal input?

**Comment by WhiteCzar** [comment]
Actually, this bug is only apparent if you type two illegal code bits. So if there is only one illegal code bit, then there is no error sound upon deleting it, but if you type two illegal code bits, then every code bit you typed after the very first mistyped code bit will produce an error sound upon Backspace-erasing it.
So maybe this is actually a feature not a bug?
