### ISSUE TITLE
auto generated goucima has something wrong for erbi-qs

### ISSUE THREAD

**Issue by simsilver** [kaio/ibus-table#77]
goucima would be auto generated if not manual configured, by selecting the longest coding for one character. The erbi-qs in ibus-table-chinese has some auxiliary code for input by pure structure or pure pronounce, which being selected for goucima.

for example:
`SELECT * from phrases where phrase='松';`
sx | 松
sxr. | 松
isong | 松

`select * from goucima where zi='松';`
松 | isong

but the right goucima for '松' should be sxr.

In erbi-qs table, the auxiliary code was put after zzzz, maybe we could add another tag for auxiliary code, and skip the tagged table for goucima.

**Comment by mike-fabian** [comment]
Fixed in https://github.com/mike-fabian/ibus-table/releases/tag/1.15.0

Thank you very much for your patches!
