### ISSUE TITLE
[BUG] Ibus input delay problem

### ISSUE THREAD

**Issue by Ray2310** [kaio/ibus-table#83]
In the Ubuntu 22.04 environment, when using ibus-table, input often becomes unresponsive and text is output after waiting for a while. The current temporary solution is to set a shortcut key to restart ibus. Restart ibus every time it freezes, but this is very troublesome. affect the user experience.

**Comment by mike-fabian** [comment]
Do you find anything interesting in `~/.cache/ibus-table/debug.log`?

Maybe set the debug level to at least 3 in the setup tool and then attach the debug.log here.

**Comment by Ray2310** [comment]
> Do you find anything interesting in `~/.cache/ibus-table/debug.log`?
> 
> Maybe set the debug level to at least 3 in the setup tool and then attach the debug.log here.

Sorry sir, I have changed the input method and my file `~/.cache/ibus-table/debug.log` is null
